openapi: 3.0.0
info:
  title: API de Productos
  version: "1.0.0"
paths:
  /auth:
    post:
      summary: "Autenticación de usuario"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                contrasena:
                  type: string
      responses:
        '200':
          description: "Autenticación exitosa"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '500':
          description: "Fallo autenticando"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: "Credenciales incorrectas"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /refresh_token:
    post:
      summary: "Actualización de token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: "Actualización exitosa"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '400':
          description: "JSON invalido"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: "Refresh token inválido o expirado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /create_product:
    post:
      summary: "Creacion de producto"
      parameters:
        - name: AUTHORIZATION
          in: header
          description: "Token de autorización para acceder al endpoint"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '202':
          description: "Se encola la creación del producto"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: "Fallo al encolar producto para su creación"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /queue_info/{queue_id}:
    get:
      summary: "Consulta sobre el proceso encolado"
      parameters:
        - name: queue_id
          in: path
          description: "ID de la cola del proceso a buscar"
          required: true
          schema:
            type: string
        - name: AUTHORIZATION
          in: header
          description: "Token de autorización para acceder al endpoint"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Devuelve el estado del proceso encolado o el producto"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/product'
                  - $ref: '#/components/schemas/status_queue'
        '400':
          description: "Fallo al buscar el proceso encolado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: "Proceso encolado no encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /product/{product_id}:
    get:
      summary: "Consulta sobre el producto"
      parameters:
        - name: product_id
          in: path
          description: "ID del producto a buscar"
          required: true
          schema:
            type: string
        - name: AUTHORIZATION
          in: header
          description: "Token de autorización para acceder al endpoint"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Devuelve el producto buscado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        '400':
          description: "Fallo al buscar el producto"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: "Producto no encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - name

    status_queue:
      type: string
      enum:
        - in_queue
        - processing
        - done 